BiocManager::install("impute")
BiocManager::install("pcaMethods")
BiocManager::install("globaltest")
BiocManager::install("GlobalAncova")
BiocManager::install("Rgraphviz")
BiocManager::install("preprocessCore")
BiocManager::install("genefilter")
BiocManager::install("qvalue")
BiocManager::install("limma")
install.packages("./SSPA_2.10.0.tar.gz", repos = NULL, type="source")
BiocManager::install("sva")
BiocManager::install("KEGGgraph")
BiocManager::install("siggenes")
BiocManager::install("BiocParallel")
BiocManager::install("MSnbase")
BiocManager::install("multtest")
BiocManager::install("RBGL")
BiocManager::install("edgeR")
BiocManager::install("fgsea")
install.packages("crmn")
install.packages("testthat")
install.packages("pkgload") 
install.packages("RJSONIO")
install.packages("fitdistrplus")
devtools::install_github("xia-lab/MetaboAnalystR@v3.3.0", build = TRUE, build_vignettes = FALSE)

